--- 
title: "Book Template"
author: "Caltech Library"
date: "`r Sys.Date()`"
url: 'https\://library.caltech.edu/'
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: AtlasBibTeX.bib
csl: springer-socpsych-brackets.csl
link-citations: yes
description: "A basic bookdown demo."
always_allow_html: true
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#This variable defines whether the online or offline form of the movies are used
offline=FALSE
```

# Introduction {#introduction}

Welcome to a demo of using bookdown to create an electronic textbook.

## Markdown syntax
Markdown is a simple text-based way of formatting documents. There are many flavors of markdown, we'll start with standard markdown and then add some specific rmarkdown information. Let's look at some other basics:

- You can put text into *italics* and **bold** using \* or \*\*
- To create headings, put one or more \# symbols at the beginning of a line, followed by a space. One \# is for a level one header, \#\# for a level two header, etc.
- To make bullet lists (such as this one), just start lines with a -; you can get additional levels by starting a line a couple of spaces or a tab in. Numbered lists work the same way using 1. 2. 3.

```
    - Topic 1
    - Topic 2  
    - Topic 3
      - Topic 3a
```
  
- To cite code (including markdown syntax as above) use \` on both sides for short bits and  \`\`\` in a separate line above and below larger codeblocks.

- Quote text using > at the beginning of the line (maybe you remember this from old e-mail programs?)

  ```
  > This is a Quote
  ```

- A link is set putting the text that you want to highlight in square brackets followed by the link in round brackets. Don't forget to include http:// or https:// at the beginning of the link

  ```
  [This is a link](http://www.example.com)
  ```

You can find more markdown formatting options [here](https://bookdown.org/yihui/rmarkdown/markdown-syntax.html). Note that markdown comes in different dialects, referred to as "flavors". The basic elements above are part of a consensus referred to as [Common Markdown](http://commonmark.org/), though some of the more advanced options we'll discuss later are specific to Rmarkdown.




