install.packages("bookdown")
install.packages("htmlwidgets")
install.packages('tufte')
install.packages('formatR')
install.packages('tinytex')
tinytex::install_tinytex()
install.packages("doivideo", repos = NULL, type = "source")
install.packages("embedvideo", repos = NULL, type = "source")
